/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n4.4.2-3-gd4b7b3c03e-20220907"
#endif /* AVUTIL_FFVERSION_H */
